"""empty message

Revision ID: 15114f1daa09
Revises: 6c25ff4e775f
Create Date: 2021-12-20 17:12:05.864226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15114f1daa09'
down_revision = '6c25ff4e775f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
