"""empty message

Revision ID: 277958ddc1a1
Revises: 15114f1daa09
Create Date: 2021-12-20 17:12:19.970002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277958ddc1a1'
down_revision = '15114f1daa09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
