"""empty message

Revision ID: 59ca8a3c7529
Revises: f92685c222e7
Create Date: 2021-12-21 21:17:44.181525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ca8a3c7529'
down_revision = 'f92685c222e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
