"""empty message

Revision ID: 9c785018abc7
Revises: 277958ddc1a1
Create Date: 2021-12-20 17:12:32.850745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c785018abc7'
down_revision = '277958ddc1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
